### ISSUE TITLE
[BUG] Crash on load

### ISSUE THREAD

**Issue by serialtasted** [ManaStar/compat-o-plenty#21]
Game crashing on load with latest version

Game: 1.18.2
Forge: 40.1.73
Mod: 1.18.2-1.5.4

Previous version works fine

Log: https://pastebin.com/qMzEmDLc

**Comment by ManaStar** [comment]
There is absolutely no mention of this mod in that log aside from the mod loading, however it does mention the Snow! Real Magic! mod near the end of your log with a ClassNotFoundException so that might be your issue. Will need more info to confirm this (Mainly a crash report if possible) but I don't believe this is on our end.

**Comment by serialtasted** [comment]
Snow! Real magic is not even installed. And this only happen when I install the latest version of your mod.
It was not easy to find which one was throwing this error exactly because the name of the mod is not mentioned anywhere, my as soon as I removed it from the folder the game started and when I downgraded back to previous version it worked.

**Comment by AllThatJazz139** [comment]
Can confirm this. Instant Crash on Mod Version 1.5.4 on 1.18.2 Forge. Crash doesn't occur in 1.5.3.

Log: [latest.log](https://github.com/ManaStar/compat-o-plenty/files/9332681/latest.log)

**Comment by ManaStar** [comment]
After looking into this again it seems this was due to https://github.com/team-abnormals/blueprint/issues/164 so I think I can just close this.
